version: "3"
services:
  vpn:
    container_name: vpn
    image: azinchen/nordvpn:latest
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=
      - PASS=
      - COUNTRY=United Kingdom;Norway;Spain;Switzerland
      - CATEGORY=Dedicated IP
      - RANDOM_TOP=20
      - RECREATE_VPN_CRON=*/30 * * * *
      - NETWORK=192.168.0.0/24;192.168.122.0/24
      - OPENVPN_OPTS=--mute-replay-warnings
      - PROTOCOL=openvpn_tcp
      - CHECK_CONNECTION_URL=https://finviz.com/screener.ashx;https://www.alphavantage.co
      - CHECK_CONNECTION_CRON=* * * * *
      - CHECK_CONNECTION_ATTEMPTS=3
      - CHECK_CONNECTION_ATTEMPT_INTERVAL=5
    restart: unless-stopped
  downloader:
    container_name: downloader
    image: downloader:0.0.1
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=should_be_really_random
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:pass@mysql:3306/forwardview
      - DATA_DIR=/forwardview-data
    restart: unless-stopped
    volumes:
      - /home/stipe/Documents/forwardview-data/data:/forwardview-data
    command: python3 downloader/downloader.py
    network_mode: service:vpn