version: "3.5"
services:
  downloader:
    container_name: downloader
    image: downloader:0.0.1
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:pass@mysql:3306/forwardview
      - DATA_DIR=/forwardview-data
    restart: unless-stopped
    volumes:
      - /home/stipe/Documents/forwardview-data/data:/forwardview-data
    command: python3 downloader/downloader.py
