version: "2"

services:
#  forwardview-1:
#    container_name: forwardview-1
#    image: forwardview:0.0.1
#    restart: unless-stopped
#    ports:
#      - 5001:5001
#    environment:
#      - FLASK_ENV=production
#      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:pass@mysql:3306/forwardview
#      - DATA_DIR=/forwardview-data
#      - CACHE_TYPE=RedisCache
#      - CACHE_REDIS_URL=redis://redis:6379/0
#      - CACHE_DEFAULT_TIMEOUT=300
#    volumes:
#      - /home/stipe/Documents/forwardview-data/data:/forwardview-data
#    command: waitress-serve --port=5001 --call app:create_app
#    depends_on:
#      mysql:
#        condition: service_healthy
#  forwardview-2:
#    container_name: forwardview-2
#    image: forwardview:0.0.1
#    restart: unless-stopped
#    ports:
#      - 5002:5002
#    environment:
#      - FLASK_ENV=production
#      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:pass@mysql:3306/forwardview
#      - DATA_DIR=/forwardview-data
#      - CACHE_TYPE=RedisCache
#      - CACHE_REDIS_URL=redis://redis:6379/0
#      - CACHE_DEFAULT_TIMEOUT=300
#    volumes:
#      - /home/stipe/Documents/forwardview-data/data:/forwardview-data
#    command: waitress-serve --port=5002 --call app:create_app
#    depends_on:
#      mysql:
#        condition: service_healthy
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    ports:
      - 3308:3306
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: pass
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./:/docker-entrypoint-initdb.d
      - /home/stipe/Documents/forwardview-data/mysql:/var/lib/mysql
  redis:
    container_name: redis
    image: "redis:alpine"
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /home/stipe/Documents/forwardview-data/redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 20s
      retries: 10
#  nginx:
#    container_name: nginx
#    image: nginx:alpine
#    restart: always
#    ports:
#      - 80:80
#      - 443:443
#    volumes:
#        - ./:/etc/nginx