version: "3.5"
services:
  vpn:
    container_name: vpn
    image: azinchen/nordvpn:latest
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
    environment:
      - USER=cirko502@gmail.com
      - PASS=
      - COUNTRY=United Kingdom;Norway;Spain;Switzerland
      - CATEGORY=Dedicated IP
      - RANDOM_TOP=20
      - RECREATE_VPN_CRON=0 * * * *
      - NETWORK=10.16.0.0/16;10.106.0.0/20
      - OPENVPN_OPTS=--mute-replay-warnings
      - PROTOCOL=openvpn_tcp
      - CHECK_CONNECTION_URL=https://finviz.com/screener.ashx;https://www.alphavantage.co
      - CHECK_CONNECTION_CRON=*/5 * * * *
      - CHECK_CONNECTION_ATTEMPTS=3
      - CHECK_CONNECTION_ATTEMPT_INTERVAL=5
    restart: unless-stopped
  downloader:
    container_name: downloader
    image: downloader:0.0.1
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:pass@138.68.128.219:3308/forwardview
      - DATA_DIR=/forwardview-data
    restart: unless-stopped
    volumes:
      - /home/forwardview-data/data:/forwardview-data
    command: python3 downloader/downloader.py
    network_mode: service:vpn
