version: "3.5"

services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    ports:
      - 3308:3306
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: pass
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./:/docker-entrypoint-initdb.d
      - /home/forwardview-data/mysql:/var/lib/mysql
    networks:
      - fw
  redis:
    container_name: redis
    image: "redis:alpine"
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /home/forwardview-data/redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 20s
      retries: 10
    networks:
      - fw
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
        - ./:/etc/nginx
    networks:
      - fw

networks:
  fw:
    name: fw-network