version: "3.5"

services:
  yuno-1:
    container_name: yuno-1
    image: yuno
    restart: unless-stopped
    ports:
      - 5001:5001
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=vq_yhf01AI75qanpo{rp8CFiH&4ibbRvM2Uhb{xP
      - STATIC_DIR=/static
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:pass@mysql:3306/forwardview
      - DATA_DIR=/forwardview-data
      - CACHE_TYPE=RedisCache
      - CACHE_REDIS_URL=redis://redis:6379/0
      - CACHE_DEFAULT_TIMEOUT=300
    volumes:
      - /home/forwardview-data/data:/forwardview-data
      - /home/forwardview/static:/static
    command: waitress-serve --port=5001 --call app:create_app
    depends_on:
      mysql:
        condition: service_healthy
  yuno-2:
    container_name: yuno-2
    image: yuno
    restart: unless-stopped
    ports:
      - 5002:5002
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=GPtdLuIR8IUe2q[/Git1UPkO7y/9/QjIaML}qsCA
      - STATIC_DIR=/static
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:pass@mysql:3306/forwardview
      - DATA_DIR=/forwardview-data
      - CACHE_TYPE=RedisCache
      - CACHE_REDIS_URL=redis://redis:6379/0
      - CACHE_DEFAULT_TIMEOUT=300
    volumes:
      - /home/forwardview-data/data:/forwardview-data
      - /home/forwardview/static:/static
    command: waitress-serve --port=5002 --call app:create_app
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    ports:
      - 3308:3306
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: pass
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./:/docker-entrypoint-initdb.d
      - /home/forwardview-data/mysql:/var/lib/mysql
  redis:
    container_name: redis
    image: "redis:alpine"
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /home/forwardview-data/redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 20s
      retries: 10
  nginx:
    container_name: nginx
    image: nginx-lets-encrypt
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/letsencrypt:/etc/letsencrypt
      - /home/forwardview/static:/static
